name: "react ci pipeline"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
       # Set up Node.js
    steps:
      - name: "setup node js"
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: "version check"
        run: node --version

      - name: "clone repo"
        uses: actions/checkout@v2

        # Install dependencies
      - name: "Install dependencies"
        run: npm install